insert ignore into categories(category_name) values ('MALE_CLOTHES');
insert ignore into categories(category_name) values ('FEMALE_CLOTHES');
insert ignore into categories(category_name) values ('GOODS_ACCESSORY');
insert ignore into categories(category_name) values ('SHOES');
insert ignore into categories(category_name) values ('SPORTS');
insert ignore into categories(category_name) values ('BOOKS');
insert ignore into categories(category_name) values ('ELECTRONICS');
insert ignore into categories(category_name) values ('FURNITURE_INTERIOR');
insert ignore into categories(category_name) values ('HOME_ELECTRONICS');
