insert into categories(category_name) values ('MALE_CLOTHES');
insert into categories(category_name) values ('FEMALE_CLOTHES');
insert into categories(category_name) values ('GOODS_ACCESSORY');
insert into categories(category_name) values ('SHOES');
insert into categories(category_name) values ('SPORTS');
insert into categories(category_name) values ('BOOKS');
insert into categories(category_name) values ('ELECTRONICS');
insert into categories(category_name) values ('FURNITURE_INTERIOR');
insert into categories(category_name) values ('HOME_ELECTRONICS');
